// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELN3dH0E7Z6zQFdIhb2CGb4M4CXjiiT0',
    appId: '1:1072056605759:web:620f7b9516b0a115a3ec8a',
    messagingSenderId: '1072056605759',
    projectId: 'chat-app-a9679',
    authDomain: 'chat-app-a9679.firebaseapp.com',
    storageBucket: 'chat-app-a9679.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dsTJwueE04i9dBM57ClaEWVn10de6A4',
    appId: '1:1072056605759:android:aa8b23f288f43474a3ec8a',
    messagingSenderId: '1072056605759',
    projectId: 'chat-app-a9679',
    storageBucket: 'chat-app-a9679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKX9LBDNrLTKVziIoqONasTWiyWEegx4',
    appId: '1:1072056605759:ios:c50a1c3584583dcea3ec8a',
    messagingSenderId: '1072056605759',
    projectId: 'chat-app-a9679',
    storageBucket: 'chat-app-a9679.appspot.com',
    iosBundleId: 'com.example.flutterApplicationChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKX9LBDNrLTKVziIoqONasTWiyWEegx4',
    appId: '1:1072056605759:ios:c50a1c3584583dcea3ec8a',
    messagingSenderId: '1072056605759',
    projectId: 'chat-app-a9679',
    storageBucket: 'chat-app-a9679.appspot.com',
    iosBundleId: 'com.example.flutterApplicationChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAELN3dH0E7Z6zQFdIhb2CGb4M4CXjiiT0',
    appId: '1:1072056605759:web:684d9ffdf6f5c43aa3ec8a',
    messagingSenderId: '1072056605759',
    projectId: 'chat-app-a9679',
    authDomain: 'chat-app-a9679.firebaseapp.com',
    storageBucket: 'chat-app-a9679.appspot.com',
  );
}
